# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Employee(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, photo_urls: str=None):  # noqa: E501
        """Employee - a model defined in Swagger

        :param id: The id of this Employee.  # noqa: E501
        :type id: int
        :param name: The name of this Employee.  # noqa: E501
        :type name: str
        :param photo_urls: The photo_urls of this Employee.  # noqa: E501
        :type photo_urls: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'photo_urls': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'photo_urls': 'photoUrls'
        }

        self._id = id
        self._name = name
        self._photo_urls = photo_urls

    @classmethod
    def from_dict(cls, dikt) -> 'Employee':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Employee of this Employee.  # noqa: E501
        :rtype: Employee
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Employee.


        :return: The id of this Employee.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Employee.


        :param id: The id of this Employee.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Employee.


        :return: The name of this Employee.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Employee.


        :param name: The name of this Employee.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def photo_urls(self) -> str:
        """Gets the photo_urls of this Employee.


        :return: The photo_urls of this Employee.
        :rtype: str
        """
        return self._photo_urls

    @photo_urls.setter
    def photo_urls(self, photo_urls: str):
        """Sets the photo_urls of this Employee.


        :param photo_urls: The photo_urls of this Employee.
        :type photo_urls: str
        """
        if photo_urls is None:
            raise ValueError("Invalid value for `photo_urls`, must not be `None`")  # noqa: E501

        self._photo_urls = photo_urls
